<?php
/**
 * LoyaltyCustomersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Secuconnect\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Secuconnect\Client\Api;

use PHPUnit\Framework\TestCase;
use Secuconnect\Client\ApiException;
use Secuconnect\Client\Model\LoyaltyCustomersList;

use Secuconnect\Client\Model\LoyaltyCustomersProductModel;
use Secuconnect\Client\Model\LoyaltyCustomersDTO;
use Secuconnect\Client\Model\Contact;
use Secuconnect\Client\Model\Address;


/**
 * LoyaltyCustomersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Secuconnect\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LoyaltyCustomersApiTest extends TestCase
{
    

    /**
     * @var LoyaltyCustomersApi
     */
    private static $api;

    /**
     * @var SecuconnectObjects
     */
    private static $instance;
    /**
     * @var obj
     */
    private static $receivedCustomer;
    
    /**
     * @var string
     */
    private static $idPaymentContainer;
    /**
     * @var string
     */
    private static $dumyCustomerId;
    
    /**
     * @var LoyaltyCustomersDTO
     */
    private static $dumyCustomer;

    /**
     * Setup before running any test cases
     *
     * @throws ApiException
     */
    public static function setUpBeforeClass()
    {
        self::$instance = SecuconnectObjects::getInstance();
        self::$instance->authenticateByApplicationUser();
        self::$api = new LoyaltyCustomersApi();
        self::$dumyCustomer = new LoyaltyCustomersDTO();
        self::$dumyCustomer->setCustomernumber('testnr');
        self::$dumyCustomer->setNote('test');
        self::$dumyCustomer->setAge('30');
        self::$dumyCustomer->setDaysUntilBirthday('23');
        self::$dumyCustomer->setAdditionalData('test data');
        
        $oAddress = new Address();
        $oAddress->setStreet('Example Street');
        $oAddress->setStreetNumber('9');
        $oAddress->setCity('Examplecity');
        $oAddress->setPostalCode('01234');
        $oAddress->setCountry('Germany');
        
        $oMerchantContact = new Contact();
        $oMerchantContact->setForename('John');
        $oMerchantContact->setSurname('Test');
        $oMerchantContact->setCompanyname('Example Inc.');
        $oMerchantContact->setSalutation('Mr.');
        $oMerchantContact->setGender('m');
        $oMerchantContact->setTitle('Dr.');
        $oMerchantContact->setEmail('email@example.com');
        $oMerchantContact->setPhone('123456789');
        $oMerchantContact->setMobile('987654321');
        $oMerchantContact->setDob('1901-02-03');
        $oMerchantContact->setUrlWebsite('example.com');
        $oMerchantContact->setBirthplace('Example Birthplace');
        $oMerchantContact->setNationality('Germany');
        $oMerchantContact->setAddress($oAddress);
        
        self::$dumyCustomer->setMerchantContact($oMerchantContact);
        
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
         self::$receivedCustomer = null;
         self::$idPaymentContainer = null;
    }
    private function chceckLoyaltyCustomersProductModel($customer)
    {
        $this->assertInstanceOf(LoyaltyCustomersProductModel::class, $customer);
        $this->assertNotEmpty($customer->getObject());
        $this->assertNotEmpty($customer->getId());
        $this->assertNotEmpty($customer->getMerchant());
        $this->assertNotEmpty($customer->getMerchant()->getObject());
        $this->assertNotEmpty($customer->getMerchant()->getId());

        $aPaymentContainers = $customer->getPaymentContainer();
        if(!empty($aPaymentContainers))
        {
            foreach($aPaymentContainers as $aPaymentContainer)
            {
                $this->assertNotEmpty($aPaymentContainer->getId());
                $this->assertNotEmpty($aPaymentContainer->getType());
                $this->assertNotEmpty($aPaymentContainer->getPaymentInformation());
                $this->assertNotEmpty($aPaymentContainer->getPaymentInformation()->getOwner());
                $this->assertNotEmpty($aPaymentContainer->getPaymentInformation()->getIban());
                $this->assertNotEmpty($aPaymentContainer->getPaymentInformation()->getBic());
                $this->assertNotEmpty($aPaymentContainer->getPaymentInformation()->getBankname());
            }
            $idPaymentContainer = $aPaymentContainer->getId();
            if(empty(self::$receivedCustomer))
            {
                self::$idPaymentContainer = $idPaymentContainer;
                self::$receivedCustomer = $customer;
                self::$dumyCustomer->setMerchant($customer->getMerchant()->getId());
            }
        }

//        Disabled forename check, because it's not set always:
//        $this->assertNotEmpty($customer->getMerchantContact()->getForename());
        $this->assertNotEmpty($customer->getMerchantContact()->getSurname());

        $this->assertNotEmpty($customer->getMerchantContact()->getAddress());
        $this->assertNotEmpty($customer->getMerchantContact()->getAddress()->getStreet());
        $this->assertNotEmpty($customer->getMerchantContact()->getAddress()->getStreetNumber());
        $this->assertNotEmpty($customer->getMerchantContact()->getAddress()->getPostalCode());
        $this->assertNotEmpty($customer->getMerchantContact()->getAddress()->getCity());

        $this->assertNotEmpty($customer->getContact()->getForename());
        $this->assertNotEmpty($customer->getContact()->getSurname());
        $this->assertNotEmpty($customer->getContact()->getAddress());
        $this->assertNotEmpty($customer->getContact()->getAddress()->getStreet());
        $this->assertNotEmpty($customer->getContact()->getAddress()->getStreetNumber());
        $this->assertNotEmpty($customer->getContact()->getAddress()->getPostalCode());
        $this->assertNotEmpty($customer->getContact()->getAddress()->getCity());

        $this->assertNotEmpty($customer->getCustomernumber());
        $this->assertNotEmpty($customer->getCreated());
    }

    /**
     * Test case for loyaltyCustomersGet
     *
     * GET Loyalty/Customers.
     *
     * @throws ApiException
     */
    public function testLoyaltyCustomersGet()
    {
        try {
            $response = self::$api->getAll();
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }  
        
        $this->assertNotEmpty($response);
        $this->assertInstanceOf(LoyaltyCustomersList::class, $response);
        
        $this->assertInternalType('int', $response->getCount());
        if (is_int($response->getCount()) && $response->getCount() > 0) {
            foreach ($response->getData() as $customer) {
                $this->chceckLoyaltyCustomersProductModel($customer);
            }
        }
    }

    /**
     * Test case for loyaltyCustomersGet
     *
     * GET Loyalty/Customers.
     *
     * @throws ApiException
     */
    public function testLoyaltyCustomersGetById()
    {
        try {
            $response = self::$api->getOne(self::$receivedCustomer->getId());
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        $this->assertNotEmpty($response);
        $this->assertInstanceOf(LoyaltyCustomersProductModel::class, $response);
        $this->assertEquals(self::$receivedCustomer, $response);
    }


    /**
     * Test case for loyaltyCustomersLoyaltyCustomerIdAssignPaymentcontainerLoyaltyPaymentcontainerIdDelete
     *
     * DELETE Loyalty/Customers/{loyaltyCustomerId}/assignPaymentcontainer/{loyaltyPaymentcontainerId}.
     *
     * @throws ApiException
     */
    public function testRemoveAssignPaymentcontainer()
    {

       try {
            $response = self::$api->removeAssignedPaymentContainer(self::$receivedCustomer->getId(), self::$idPaymentContainer);
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }
        $aPaymentContainers = $response->getPaymentContainer();
        $paymentcontainerExist = false;
        if (!empty($aPaymentContainers))
        {
            foreach($aPaymentContainers as $aPaymentContainer)
            {
                if($aPaymentContainer->getId() === self::$idPaymentContainer)
                {
                    $paymentcontainerExist = true;
                }
            }
        }
        $this->assertFalse($paymentcontainerExist);
         
    }

    /**
     * Test case for loyaltyCustomersLoyaltyCustomerIdAssignPaymentcontainerLoyaltyPaymentcontainerIdPost
     *
     * POST Loyalty/Customers/{loyaltyCustomerId}/assignPaymentcontainer/{loyaltyPaymentcontainerId}.
     *
     * @throws ApiException
     */
    public function testAddAssignPaymentcontainer()
    {
        try {
            $response = self::$api->assignPaymentContainer(self::$receivedCustomer->getId(), self::$idPaymentContainer);
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }
        $aPaymentContainers = $response->getPaymentContainer();
        $paymentcontainerExist = false;
        if (!empty($aPaymentContainers))
        {
            foreach($aPaymentContainers as $aPaymentContainer)
            {
                if($aPaymentContainer->getId() === self::$idPaymentContainer)
                {
                    $paymentcontainerExist = true;
                }
            }
        }
        $this->assertTrue($paymentcontainerExist);
    }

    /**
     * Test case for loyaltyCustomersLoyaltyCustomerIdCheckDuplicatedPost
     *
     * POST Loyalty/Customers/{loyaltyCustomerId}/checkDuplicated/.
     *
     * @throws ApiException
     */
    public function testcheckDuplicated()
    {
        try {
            $response = self::$api->checkForDuplicates(self::$receivedCustomer->getMerchant()->getId());
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }
        $array =  (array) $response;
        $this->assertArrayHasKey('customers_without_merchantcard', $array);
        $this->assertArrayHasKey('duplicated_customers', $array);
    }

    /**
     * Test case for loyaltyCustomersLoyaltyCustomerIdPost
     *
     * POST Loyalty/Customers/{loyaltyCustomerId}.
     *
     * @throws ApiException
     */
    public function testaddCustomer()
    {
        try {
            $response = self::$api->addCustomer(self::$dumyCustomer);
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }
        self::$dumyCustomerId = $response->getId();
       $this->chceckLoyaltyCustomersProductModel($response);
        
    }

    /**
     * Test case for
     *
     * PUT Loyalty/Customers/{loyaltyCustomerId}.
     *
     * @throws ApiException
     */
    public function testupdateCustomer()
    {
        try {
            self::$dumyCustomer->setNote('Test Update');
            $oMerchantContactTestUpdate = clone self::$dumyCustomer->getMerchantContact();
            $oMerchantContactTestUpdate->setSurname('Test Surname');
            self::$dumyCustomer->setMerchantContact($oMerchantContactTestUpdate);
            $response = self::$api->updateCustomer(self::$dumyCustomerId,self::$dumyCustomer);
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }
        $this->assertEquals(self::$dumyCustomer->getMerchantContact()->getSurname(), $response->getMerchantContact()->getSurname());
        $this->assertEquals(self::$dumyCustomer->getNote(), $response->getNote());
    }

    /**
     * Test case for loyaltyCustomersLoyaltyCustomerIdDelete
     *
     * DELETE Loyalty/Customers/{loyaltyCustomerId}.
     *
     * @throws ApiException
     */
    public function testremoveCustomer()
    {
        try {
            $response = self::$api->removeCustomer(self::$dumyCustomerId);
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }
        $this->assertNotEmpty('deleted', $response->getDeleted());
    }  

    
}
