<?php
/**
 * PaymentSecupayCreditcardsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Secuconnect\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SecuConnect API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Secuconnect\Client;

use Secuconnect\Client\Api\PaymentSecupayCreditcardsApi;
use Secuconnect\Client\Api\SecuconnectObjects;
use Secuconnect\Client\Model\PaymentCustomersProductModel;
use Secuconnect\Client\Model\SecupayTransactionProductModel;

/**
 * PaymentSecupayCreditcardsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Secuconnect\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentSecupayCreditcardsApiTest extends \PHPUnit_Framework_TestCase
{
    private static $secuconnectObjects;
    private static $creditCardTransactionId;
    private static $customerId;
    private static $amount;
    private static $currency;
    private static $orderId;
    private static $accrual;
    private static $basket;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
        self::$secuconnectObjects = SecuconnectObjects::getInstance();
        self::$customerId = self::$secuconnectObjects->getCustomer()->getId();
        self::$amount = 100;
        self::$currency = 'EUR';
        self::$orderId = 'ZZZZZZ';
        self::$accrual = true;
        self::$basket = self::$secuconnectObjects->getBasket();
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
        $this->api = self::$secuconnectObjects->getApi();
        $this->api = new PaymentSecupayCreditcardsApi();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
        $this->api = null;
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
        self::$secuconnectObjects = null;
        self::$creditCardTransactionId = null;
        self::$customerId = null;
        self::$amount = null;
        self::$currency = null;
        self::$orderId = null;
        self::$accrual = null;
        self::$basket = null;
    }

    /**
     * Test case for paymentSecupaycreditcardsPost
     */
    public function testPaymentSecupaycreditcardsPost()
    {
        $creditCardData = [
            "customer" => self::$customerId,
            "amount" => self::$amount,
            "currency" => self::$currency,
            "order_id" => self::$orderId,
            "accrual" => self::$accrual,
            "basket" => self::$basket
        ];

        try {
            $response = $this->api->paymentSecupaycreditcardsPost($creditCardData);
            self::$creditCardTransactionId = $response->getId();
        } catch (\Secuconnect\Client\ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        $this->assertNotEmpty(self::$creditCardTransactionId);
        $this->assertInstanceOf(SecupayTransactionProductModel::class, $response);
        $this->assertEquals('payment.secupaycreditcards', $response->getObject());
        $this->assertEquals(self::$creditCardTransactionId, $response->getId());
        $this->assertNotEmpty($response->getTransId());
        $this->assertNotEmpty($response->getStatus());
        $this->assertEquals(self::$amount, $response->getAmount());
        $this->assertEquals(self::$currency, $response->getCurrency());
        $this->assertNull($response->getPurpose());
        $this->assertEquals(self::$orderId, $response->getOrderId());

        for ($i = 0; $i < 3; $i++) {
            $this->assertEquals(self::$basket[$i], $response->getBasket()[$i]);
            $this->assertEquals(self::$basket[$i]->getItemType(), $response->getBasket()[$i]->getItemType());
            $this->assertEquals(self::$basket[$i]->getArticleNumber(), $response->getBasket()[$i]->getArticleNumber());
            $this->assertEquals(self::$basket[$i]->getQuantity(), $response->getBasket()[$i]->getQuantity());
            $this->assertEquals(self::$basket[$i]->getName(), $response->getBasket()[$i]->getName());
            $this->assertEquals(self::$basket[$i]->getModel(), $response->getBasket()[$i]->getModel());
            $this->assertEquals(self::$basket[$i]->getEan(), $response->getBasket()[$i]->getEan());
            $this->assertEquals(self::$basket[$i]->getTax(), $response->getBasket()[$i]->getTax());
            $this->assertEquals(self::$basket[$i]->getTotal(), $response->getBasket()[$i]->getTotal());
            $this->assertEquals(self::$basket[$i]->getPrice(), $response->getBasket()[$i]->getPrice());
            $this->assertEquals(self::$basket[$i]->getApikey(), $response->getBasket()[$i]->getApikey());
            $this->assertEquals(self::$basket[$i]->getTransactionHash(), $response->getBasket()[$i]->getTransactionHash());
            $this->assertEquals(self::$basket[$i]->getContractId(), $response->getBasket()[$i]->getContractId());
        }

        $this->assertEquals(1, $response->getTransactionStatus());
        $this->assertEquals(self::$accrual, $response->getAccrual());
        $this->assertEquals('sale', $response->getPaymentAction());
        $this->assertNotEmpty($response->getCustomer());
        $this->assertEquals('payment.customers', $response->getCustomer()->getObject());
        $this->assertEquals(self::$customerId, $response->getCustomer()->getId());
        $this->assertNotEmpty($response->getCustomer()->getContract());
        $this->assertEquals('payment.contracts', $response->getCustomer()->getContract()->getObject());
        $this->assertNotEmpty($response->getCustomer()->getContract()->getId());
        $this->assertNotEmpty($response->getCustomer()->getCreated());
        $this->assertNotEmpty($response->getRedirectUrl());
        $this->assertNotEmpty($response->getRedirectUrl()['iframe_url']);
        $this->assertNotEmpty($response->getRedirectUrl()['url_success']);
        $this->assertNotEmpty($response->getRedirectUrl()['url_failure']);
        $this->assertNotEmpty($response->getIframeUrl());
    }

    /**
     * Test case for paymentSecupaycreditcardsHashGet
     */
    public function testPaymentSecupayCreditcardsGetById()
    {
        try {
            $response = $this->api->paymentSecupayCreditcardsGetById(self::$creditCardTransactionId);
        } catch (\Secuconnect\Client\ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        $this->assertNotEmpty(self::$creditCardTransactionId);
        $this->assertInstanceOf(SecupayTransactionProductModel::class, $response);
        $this->assertEquals('payment.secupaycreditcards', $response->getObject());
        $this->assertEquals(self::$creditCardTransactionId, $response->getId());
        $this->assertNotEmpty($response->getTransId());
        $this->assertNotEmpty($response->getStatus());
        $this->assertEquals(self::$amount, $response->getAmount());
        $this->assertEquals(self::$currency, $response->getCurrency());
        $this->assertEmpty($response->getPurpose());
        $this->assertEquals(self::$orderId, $response->getOrderId());

        for ($i = 0; $i < 3; $i++) {
            $this->assertEquals(self::$basket[$i], $response->getBasket()[$i]);
            $this->assertEquals(self::$basket[$i]->getItemType(), $response->getBasket()[$i]->getItemType());
            $this->assertEquals(self::$basket[$i]->getArticleNumber(), $response->getBasket()[$i]->getArticleNumber());
            $this->assertEquals(self::$basket[$i]->getQuantity(), $response->getBasket()[$i]->getQuantity());
            $this->assertEquals(self::$basket[$i]->getName(), $response->getBasket()[$i]->getName());
            $this->assertEquals(self::$basket[$i]->getModel(), $response->getBasket()[$i]->getModel());
            $this->assertEquals(self::$basket[$i]->getEan(), $response->getBasket()[$i]->getEan());
            $this->assertEquals(self::$basket[$i]->getTax(), $response->getBasket()[$i]->getTax());
            $this->assertEquals(self::$basket[$i]->getTotal(), $response->getBasket()[$i]->getTotal());
            $this->assertEquals(self::$basket[$i]->getPrice(), $response->getBasket()[$i]->getPrice());
            $this->assertEquals(self::$basket[$i]->getApikey(), $response->getBasket()[$i]->getApikey());
            $this->assertEquals(self::$basket[$i]->getTransactionHash(), $response->getBasket()[$i]->getTransactionHash());
            $this->assertEquals(self::$basket[$i]->getContractId(), $response->getBasket()[$i]->getContractId());
        }

        $this->assertEquals(1, $response->getTransactionStatus());
        $this->assertEquals(self::$accrual, $response->getAccrual());
        $this->assertEquals('sale', $response->getPaymentAction());
        $this->assertNotEmpty($response->getCustomer());
        $this->assertInstanceOf(PaymentCustomersProductModel::class, $response->getCustomer());
        $this->assertEquals('payment.customers', $response->getCustomer()->getObject());
        $this->assertEquals(self::$customerId, $response->getCustomer()->getId());
        $this->assertNotEmpty($response->getCustomer()->getContract());
        $this->assertEquals('payment.contracts', $response->getCustomer()->getContract()->getObject());
        $this->assertNotEmpty($response->getCustomer()->getContract()->getId());
        $this->assertNotEmpty($response->getCustomer()->getCreated());
        $this->assertNotEmpty($response->getRedirectUrl());
        $this->assertNotEmpty($response->getRedirectUrl()['iframe_url']);
        $this->assertNotEmpty($response->getRedirectUrl()['url_success']);
        $this->assertNotEmpty($response->getRedirectUrl()['url_failure']);
    }

    /**
     * Test case for paymentSecupaycreditcardsHashCancelPost
     */
    public function testPaymentSecupayCreditcardsCancelById()
    {
        try {
            $response = $this->api->paymentSecupayCreditcardsCancelById(self::$creditCardTransactionId);
        } catch (\Secuconnect\Client\ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        $this->assertNotEmpty($response);
        $this->assertEquals(true, $response['result']);
        $this->assertEquals(true, $response['demo']);
    }
}
