<?php
/**
 * SmartDevicesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Secuconnect\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Secuconnect API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Secuconnect\Client;

use PHPUnit\Framework\TestCase;
use Secuconnect\Client\Api\SecuconnectObjects;
use Secuconnect\Client\Configuration;
use Secuconnect\Client\ApiClient;
use Secuconnect\Client\ApiException;
use Secuconnect\Client\Model\SmartDevicesSecubaseConfig;
use Secuconnect\Client\Model\SmartDevicesSecubaseConfigLogging;
use Secuconnect\Client\Model\SmartDevicesSecubaseConfigLoggingFileNet;
use Secuconnect\Client\ObjectSerializer;
use Secuconnect\Client\Api\SmartDevicesApi;
use Secuconnect\Client\Model\SmartDevicesList;
use Secuconnect\Client\Model\SmartDevicesList1;
use Secuconnect\Client\Model\SmartDevicesProductModel;
use Secuconnect\Client\Model\SmartDevicesDTO;
use Secuconnect\Client\Model\SmartDevicesDTOSecubaseConfig;
use Secuconnect\Client\Model\SmartDevicesDTOPrepaidTid;

/**
 * SmartDevicesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Secuconnect\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SmartDevicesApiTest extends TestCase
{
    /**
     * @var SmartDevicesApi
     */
    private static $api;

    /**
     * @var SecuconnectObjects
     */
    private static $instance;

    /**
     * @var SmartDevicesList
     */
    private static $smartDevicesList;

    /**
     * @var SmartDevicesDTO
     */
    private static $smartDevicesDTO;

    /**
     * @var SmartDevicesProductModel
     */
    private static $smartDevicesProductModel;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
        self::$instance = SecuconnectObjects::getInstance();
        self::$instance->authenticateByApplicationUser();
        self::$api = new SmartDevicesApi();
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getAll
     *
     * GET Smart/Devices.
     *
     */
    public function testGetAll()
    {
        try {
            self::$smartDevicesList = self::$api->getAll();
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        $this->assertNotEmpty(self::$smartDevicesList);
        $this->assertInstanceOf(SmartDevicesList::class, self::$smartDevicesList);
        $this->assertInternalType('int', self::$smartDevicesList->getCount());

        foreach (self::$smartDevicesList->getData() as $smartDevice) {
            $this->assertInstanceOf(SmartDevicesProductModel::class, $smartDevice);
            $this->assertEquals('smart.devices', $smartDevice->getObject());
            $this->assertNotEmpty($smartDevice->getId());
            $this->assertNotEmpty($smartDevice->getMerchant());
            $this->assertNotEmpty($smartDevice->getMerchant()->getId());
            $this->assertNotEmpty($smartDevice->getStore());
            $this->assertNotEmpty($smartDevice->getStore()->getId());
            $this->assertNotEmpty($smartDevice->getVendor());
            $this->assertNotEmpty($smartDevice->getVendorUid());
            $this->assertNotEmpty($smartDevice->getType());
            $this->assertNotEmpty($smartDevice->getUserPin());
            $this->assertNotEmpty($smartDevice->getProducts());
            $this->assertNotEmpty($smartDevice->getCreated());
        }
    }

    /**
     * Test case for getOne
     *
     * GET Smart/Devices/{id}.
     */
    public function testGetOne()
    {
        try {
            $response = self::$api->getOne(self::$smartDevicesList->getData()[0]->getId());
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        $this->assertNotEmpty($response);
        $this->assertInstanceOf(SmartDevicesProductModel::class, $response);

        $this->assertEquals('smart.devices', $response->getObject());
        $this->assertNotEmpty($response->getId());
        $this->assertNotEmpty($response->getMerchant());
        $this->assertNotEmpty($response->getMerchant()->getId());
        $this->assertNotEmpty($response->getStore());
        $this->assertNotEmpty($response->getStore()->getId());
        $this->assertNotEmpty($response->getVendor());
        $this->assertNotEmpty($response->getVendorUid());
        $this->assertNotEmpty($response->getType());
        $this->assertNotEmpty($response->getCreated());
    }

    /**
     * Test case for getRouting
     *
     * GET Smart/Devices/{smartDeviceId}/routing/type/{type}.
     *
     */
    public
    function testGetRouting()
    {
        try {
            $response = self::$api->getRouting(self::$smartDevicesList->getData()[0]->getId(), self::$smartDevicesList->getData()[0]->getType());
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        // print_r($response);
        $this->assertNotEmpty($response);
        $this->assertInstanceOf(SmartDevicesList1::class, $response);
        $this->assertInternalType('int', $response->getCount());

        foreach ($response->getData() as $smartDevice) {
            $this->assertInstanceOf(SmartDevicesProductModel::class, $smartDevice);
            $this->assertEquals('smart.devices', $smartDevice->getObject());
            $this->assertNotEmpty($smartDevice->getId());
            $this->assertNotEmpty($smartDevice->getMerchant());
            $this->assertNotEmpty($smartDevice->getMerchant()->getId());
            $this->assertNotEmpty($smartDevice->getStore());
            $this->assertNotEmpty($smartDevice->getStore()->getId());
            $this->assertNotEmpty($smartDevice->getVendor());
            $this->assertNotEmpty($smartDevice->getVendorUid());
            $this->assertNotEmpty($smartDevice->getType());
            $this->assertNotEmpty($smartDevice->getCreated());
        }
    }

    /**
     * Test case for addDevice
     *
     * POST Smart/Devices.
     *
     */
    public function testAddDevice()
    {
        self::$smartDevicesDTO = new SmartDevicesDTO();
        self::$smartDevicesDTO->setMerchant(self::$smartDevicesList->getData()[0]->getMerchant()->getId());
        self::$smartDevicesDTO->setStore(self::$smartDevicesList->getData()[0]->getStore()->getId());
        self::$smartDevicesDTO->setVendor("shopware");
        self::$smartDevicesDTO->setVendorUid(rand(100000000, 999999999)); // FIXME: in real life this should be a unique UId
        self::$smartDevicesDTO->setType("cashier");

        try {
            self::$smartDevicesProductModel = self::$api->addDevice(self::$smartDevicesDTO);
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        $this->assertNotEmpty(self::$smartDevicesProductModel);
        $this->assertInstanceOf(SmartDevicesProductModel::class, self::$smartDevicesProductModel);

        $this->assertEquals('smart.devices', self::$smartDevicesProductModel->getObject());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getMerchant());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getMerchant()->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getStore());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getStore()->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getVendor());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getVendorUid());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getType());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getCreated());
    }

    /**
     * Test case for updateDevice
     *
     * PUT Smart/Devices/{id}.
     *
     */
    public
    function testUpdateDevice()
    {
        self::$smartDevicesDTO->setVendor("shopware");

        try {
            self::$smartDevicesProductModel = self::$api->updateDevice(self::$smartDevicesProductModel->getId(), self::$smartDevicesDTO);
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        $this->assertNotEmpty(self::$smartDevicesProductModel);
        $this->assertInstanceOf(SmartDevicesProductModel::class, self::$smartDevicesProductModel);

        $this->assertEquals('smart.devices', self::$smartDevicesProductModel->getObject());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getMerchant());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getMerchant()->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getStore());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getStore()->getId());
        $this->assertEquals("shopware", self::$smartDevicesProductModel->getVendor());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getVendorUid());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getType());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getCreated());
    }

    /**
     * Test case for getSecubaseConfig
     *
     * POST Smart/Devices/{id}/GetSecubaseConfig.
     *
     */
    public function testGetSecubaseConfig()
    {
        $smartDevicesDTOSecubaseConfig = new SmartDevicesDTOSecubaseConfig();
        $smartDevicesDTOSecubaseConfig->setSecubaseVersion("3.0.1-pre.2");
        $smartDevicesDTOSecubaseConfig->setBaseVersion("3.0.1-pre.1");
        $smartDevicesDTOSecubaseConfig->setOaiVersion("1.3.4");

        try {
            $response = self::$api->getSecubaseConfig(self::$smartDevicesProductModel->getId(), $smartDevicesDTOSecubaseConfig);
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        $this->assertNotEmpty($response);
        $this->assertInstanceOf(SmartDevicesSecubaseConfig::class, $response);

        $this->assertNotNull($response->getApps());     
        if(!empty( $response->getLogging()))
        {
            $this->assertInstanceOf(SmartDevicesSecubaseConfigLogging::class, $response->getLogging());
            $this->assertNotEmpty($response->getLogging()->getApp());
            $this->assertInstanceOf(SmartDevicesSecubaseConfigLoggingFileNet::class, $response->getLogging()->getApp());
            $this->assertNotEmpty($response->getLogging()->getSecubase());
            $this->assertInstanceOf(SmartDevicesSecubaseConfigLoggingFileNet::class, $response->getLogging()->getSecubase());
        }
        
    }

    /**
     * Test case for createPrepaidTid
     *
     * POST Smart/Devices/{id}/CreatePrepaidTid.
     *
     */
    public function testCreatePrepaidTid()
    {
        $smartDevicesDTOPrepaidTid = new SmartDevicesDTOPrepaidTid();
        $smartDevicesDTOPrepaidTid->setForce(false);
        $smartDevicesDTOPrepaidTid->setTid(null);

        try {
            self::$smartDevicesProductModel = self::$api->createPrepaidTid(self::$smartDevicesProductModel->getId(), $smartDevicesDTOPrepaidTid);
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        $this->assertNotEmpty(self::$smartDevicesProductModel);
        $this->assertInstanceOf(SmartDevicesProductModel::class, self::$smartDevicesProductModel);

        $this->assertEquals('smart.devices', self::$smartDevicesProductModel->getObject());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getMerchant());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getMerchant()->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getStore());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getStore()->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getVendor());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getVendorUid());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getType());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getProducts());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getProducts()->getPrepaid());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getProducts()->getPrepaid()->getVtcTid());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getCreated());
    }

    /**
     * Test case for createVirtualDevice
     *
     * POST Smart/Devices/{id}/CreateVirtualDevice.
     *
     * @group ignore
     */
    public function testCreateVirtualDevice()
    {
        try {
            self::$smartDevicesProductModel = self::$api->createVirtualDevice(self::$smartDevicesProductModel->getId());
        } catch (ApiException $e) {
            print_r($e->getResponseBody());
            throw $e;
        }

        $this->assertNotEmpty(self::$smartDevicesProductModel);
        $this->assertInstanceOf(SmartDevicesProductModel::class, self::$smartDevicesProductModel);

        $this->assertEquals('smart.devices', self::$smartDevicesProductModel->getObject());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getMerchant());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getMerchant()->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getStore());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getStore()->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getVendor());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getVendorUid());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getType());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getDevice());
        $this->assertEquals("general.devices", self::$smartDevicesProductModel->getDevice()->getObject());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getDevice()->getId());
        $this->assertNotEmpty(self::$smartDevicesProductModel->getCreated());
    }
}
